include: package:flutter_iconica_analysis/analysis_options.yaml

# Possible to overwrite the rules from the package

analyzer:
  exclude:

linter:
  rules:
    prefer_double_quotes: true
    prefer_single_quotes: false
    unnecessary_final: false
    prefer_expression_function_bodies: false
    # Allow abstract final classes with only static members (utility classes)
    avoid_classes_with_only_static_members: false


formatter:
  trailing_commas: preserve
