name: streamhub
description: "A Flutter M3U playlist streaming app for legal content."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^7.0.0
  environment_config: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - dotenv

flutter_native_splash:
  color: "#667eea"
  color_dark: "#667eea"
  android_12:
    color: "#667eea"
    color_dark: "#667eea"
  web: true
  android: true
  ios: true
